### ISSUE TITLE
need missing firmware amd gpu

### ISSUE THREAD

**Issue by Jv187** [Umio-Yasuno/unofficial-amdgpu-firmware-repo#1]
yellow_carp_gpu_info.bin
navi10_mes.bin

**Comment by Umio-Yasuno** [comment]
<https://github.com/Umio-Yasuno/unofficial-amdgpu-firmware-repo/blob/main/navi10_mes_issue.md>

`yellow_carp_gpu_info.bin` is not yet uploaded to <https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu>, nor is not included in the official driver package.
