### ISSUE TITLE
File missing:  navi10_mes.bin

### ISSUE THREAD

**Issue by sakthivelgreen** [Umio-Yasuno/unofficial-amdgpu-firmware-repo#2]
Mr. Umio-Yasuno, I have seen that a file missing in your repository.
i was facing error .
and i can't find it anywhere internet.
so please upload this navi10_mes.bin.
Thank you.

**Comment by Umio-Yasuno** [comment]
Please read [navi10_mes_issue.md](https://github.com/Umio-Yasuno/unofficial-amdgpu-firmware-repo/blob/main/navi10_mes_issue.md) and #1.
`navi10_mes.bin` is unnecessary firmware, the only problem is it is there is not one, so it just print a warning message. There is no effect.  

And I do not have that `navi10_mes.bin` firmware.
I am just collecting the AMDGPU firmware uploaded by AMD developers.
